export {default as HomePage} from './HomePage';
export {default as CocktailPage} from './CocktailPage';
export {default as AlcoholicPage} from './AlcoholicPage';
export {default as CategoriesPage} from './CategoriesPage';
export {default as GlassesPage} from './GlassesPage';
export {default as IngredientsPage} from './IngredientsPage';
export {default as CocktailsByIngredientPage} from './CocktailsByIngredientPage';
export {default as FavoritePage} from './FavoritePage';
export {default as ErrorPage} from './ErrorPage';